; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.34"

; Modules
projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"

projects[token][version] = "1.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"
